import { createApp } from 'vue';
import App from '@/App.vue';
import { registerPlugins } from '@/plugins';
import { whenLocaleReady } from '@/plugins/i18n';

// Generated by unplugin-fonts from the families declared in `vite.config.mts`.
// Without it the whole interface falls back to the system sans-serif, which looks
// like a theme nobody finished rather than a stylesheet nobody imported.
import 'unfonts.css';
import '@mdi/font/css/materialdesignicons.css';
import '@/styles/index.scss';

/*
 * Which build this is, said once where anybody can read it.
 *
 * A browser keeps a tab open across a deploy, and a stale bundle against a new gateway
 * is the one fault nobody thinks to check: the screen looks right, one call answers
 * something the interface does not expect, and the person reporting it is describing a
 * version nobody is running any more. The gateway's own version is printed beside it as
 * soon as it answers — see `stores/auth` — so the two can be compared without asking
 * anybody to open the network tab.
 */
console.info(
	`%cMedia Center Sync%c interface ${import.meta.env.VITE_APP_VERSION || 'dev'}`,
	'font-weight:600',
	'color:inherit',
);

const app = createApp(App);

registerPlugins(app);

/*
 * Mounted once the chosen catalogue is in.
 *
 * Only English is bundled; the other seven are chunks (see `plugins/i18n`). Mounting
 * before the chosen one lands paints the whole interface in English and swaps it a
 * moment later, which looks like a bug on every reload for anybody who is not reading
 * in English. The wait is one same-origin request, and it never fails the boot: a
 * catalogue that does not arrive leaves the fallback in place.
 */
void whenLocaleReady().then(() => app.mount('#app'));
