import { createApp } from 'vue';
import App from '@/App.vue';
import { registerPlugins } from '@/plugins';

// Generated by unplugin-fonts from the families declared in `vite.config.mts`.
// Without it the whole interface falls back to the system sans-serif, which looks
// like a theme nobody finished rather than a stylesheet nobody imported.
import 'unfonts.css';
import '@mdi/font/css/materialdesignicons.css';
import '@/styles/index.scss';

const app = createApp(App);

registerPlugins(app);

app.mount('#app');
